### ISSUE TITLE
Several commands are not available

### ISSUE THREAD

**Issue by ivokun** [rekriz11/DeDiv#2]
It was interesting paper for comparing many decoding strategies in conditional models. However I couldn't reproduce your work in current setup. 

I already set bert-as-service running and download uncased pre-trained model (which you linked to wrong model). However, I don't know which OpenNMT did you use for this repo. I downloaded it from https://github.com/OpenNMT/OpenNMT-py and with existing pre-trained model https://s3.amazonaws.com/opennmt-models/dialog_acc_39.74_ppl_26.63_e13.pt

I've got several errors: -replace_unk command not found and also -block_ngram_repeat didn't available.

Please update the repo with working setup. Or maybe my setup was wrong please let me know.

Thank you!

**Comment by daphnei** [comment]
Sorry for the delayed response. Unfortunately our modifications to OpenNMT were done on an earlier version of OpenNMT, and a couple months after we forked and made our changes, the decoding code on OpenNMT master was substantially rewritten. This means it has been more arduous than we expected to merge our implementations into the master.

Within the next couple weeks, we will modify this repo's README to point to our fork of OpenNMT. I'll update this issue when we do so.

**Comment by daphnei** [comment]
Closing this has the README has been updated.
